### ISSUE TITLE
“依赖与窗口”一节开始处的依赖需要更新

### ISSUE THREAD

**Issue by leosongwei** [jinleili/learn-wgpu-zh#13]
在[我们要使用哪些包?](https://github.com/jinleili/learn-wgpu-zh/blob/master/docs/beginner/tutorial1-window.md#%E6%88%91%E4%BB%AC%E8%A6%81%E4%BD%BF%E7%94%A8%E5%93%AA%E4%BA%9B%E5%8C%85)处，给出的wgpu版本太老，到了“管线（Pipeline）”一节中，该版本的wgpu无法识别着色器中的`vec4f`类型。

**Comment by jinleili** [comment]
感谢指出问题, 已修复 :)
