### ISSUE TITLE
有macos的案例吗

### ISSUE THREAD

**Issue by fromwhite** [jinleili/learn-wgpu-zh#23]
我看到了 wgpu in app 和另一个 网页的
有 macos 的案例吗， 结合 swift 开发 app

**Comment by jinleili** [comment]
所有示例都可以在 macOS 运行

**Comment by fromwhite** [comment]
mac上剔除了winit由系统接管，这种方案可以改到windows吗？
wgpu开发软件更多在专业领域，比如仿真终端，比消费端的图表类更实际，做app效果的话，目前厂商更愿意整一个u3d进去。
跨平台的桌面开发有没有可能，egui跟移动app的场景一样
