### ISSUE TITLE
能否将深度缓冲区章节的challenge实现换为使用普通sampler对深度纹理进行采样

### ISSUE THREAD

**Issue by wefcdse** [jinleili/learn-wgpu-zh#5]
现在的代码只画出了所有的五边形实例的位置，而没有画出深度
<img width="451" alt="屏幕截图 2023-03-13 111224" src="https://user-images.githubusercontent.com/99232042/224600440-490f8bac-0dea-4004-b78d-9d60df3bc261.png">
<img width="451" alt="屏幕截图 2023-03-13 111442" src="https://user-images.githubusercontent.com/99232042/224600463-4966a2ef-af8d-4b78-9d24-0d5a77d6af45.png">

**Comment by wefcdse** [comment]
图1：直接运行
图2：改了sampler之后

**Comment by jinleili** [comment]
欢迎提交代码 :)

**Comment by wefcdse** [comment]
:)
